export const tagsList = [
  "Politics",
  "Travel",
  "World",
  "Investment",
  "Crime",
  "Business",
  "Education",
  "Romance",
  "Job and Vacancies",
  "Space",
  "NASA",
  "Astrophysics",
  "Car Talk",
  "Properties",
  "Family",
  "Health",
  "Fashion",
  "Agriculture",
  "Computers",
  "Phones",
  "Graphics and Videos",
  "Programming",
  "Technology Market",
  "Jokes and Comedy",
  "Literature",
  "Entertainment",
  "Music and Radio",
  "Sports and Gaming",
  "Pets",
  "Autos",
  "NYSC",
  "Culture",
  "Religion",
  "Food",
  "Diaries",
  "Webmasters",
  "Art",
  "Finance",
];
